
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import "gameObject.sol";

contract baseStation is gameObject{
    gameObject[] units;

    function getDefencePower() internal override
    {
        tvm.accept();
        defencePower = 3;
    }

    function addWarUnit(gameObject a) public
    {
        tvm.accept();
        units.push(a);
    }

    function deleteUnit(address a) public 
    {
        tvm.accept();
        uint8 index;
        for (uint8 i = 0; i < units.length; ++i)
        {
            if (a == units[i]) 
            {
                index = i;
                break;
            }
        }
        gameObject[] buffArr;
        for (uint8 i = 0; i < index; ++i)
        {
            buffArr.push(units[i]);
        }
        for (uint8 i = index + 1; i < units.length; ++i)
        {
            buffArr.push(units[i]);
        }
        units = buffArr;
    }

    function dead() internal override
    {
        tvm.accept();
        if (health <= 0)
        {
            for (uint8 i = 0; i < units.length; ++i)
        {
            units[i].selfDestruction(attackerAddress);
        }
            selfDestruction(attackerAddress);
        }
    }
}
